name: futu_trade
channels:
  - defaults
dependencies:
  - beautifulsoup4=4.9.3
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cryptography=3.4.7
  - et_xmlfile=1.0.1
  - html5lib=1.1
  - humanize=3.5.0
  - idna=2.10
  - importlib_metadata=3.10.0
  - intel-openmp=2021.2.0
  - jdcal=1.4.1
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - numpy-base=1.20.1
  - openpyxl=3.0.5
  - openssl=1.1.1k
  - pandas=1.2.0
  - pycparser=2.20
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.1
  - pytz=2021.1
  - requests=2.25.1
  - six=1.15.0
  - soupsieve=2.2.1
  - sqlite=3.35.4
  - urllib3=1.26.4
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - webencodings=0.5.1
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xlrd=2.0.1
  - yaml=0.2.5
  - zipp=3.4.1
  - pip:
      - backtesting==0.3.1
      - bokeh==2.3.0
      - cx-freeze==6.6
      - cx-logging==3.0
      - docopt==0.6.2
      - empyrical==0.5.5
      - futu-api==5.2.1408
      - importlib-metadata==4.0.1
      - joblib==1.0.0
      - kids-cache==0.0.7
      - lxml==4.6.3
      - multitasking==0.0.9
      - numpy==1.19.3
      - pandas-datareader==0.9.0
      - pip==21.1.1
      - pipreqs==0.4.10
      - protobuf==3.5.1
      - pycryptodome==3.9.9
      - pyfolio==0.9.2
      - pypiwin32==223
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.8.1
      - pyqtgraph==0.12.1
      - pyside6==6.0.3
      - pyxlsb==1.0.7
      - pyyaml==5.4.1
      - scikit-learn==0.24.1
      - scipy==1.6.0
      - seaborn==0.11.1
      - setuptools==56.2.0
      - shiboken6==6.0.3
      - simplejson==3.17.2
      - ta-lib==0.4.19
      - threadpoolctl==2.1.0
      - tqdm==4.59.0
      - tulipy==0.4.0
      - typing==3.7.4
      - typing-extensions==3.7.4.3
      - yarg==0.1.9
      - yfinance==0.1.59
