name: Python Package using Conda

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          conda create --name futu_trade --file requirements.txt
      - name: Test with Python
        run: |
          python main_backend.py
      - name: Build EXE file
        run: |
          python setup.py build
